language: elixir

elixir:
  - 1.5.3
  - 1.6.6

otp_release:
  - 19.3.6
  - 20.3.8
  - 21.0.1

env:
  - MIX_ENV=test

matrix:
  exclude:
  - elixir: 1.5.3
    otp_release: 21.0.1

script: mix coveralls.travis
